[package]
name = "lazyv2ex"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
reqwest = { version = "0.11", features = ["blocking"] }
rss = "2.0"
chrono = "0.4"
